// This file was auto-generated by Fern from our API Definition.

export interface ProductConfig {
    developer?: ProductConfig.Developer | undefined;
    projectroom?: ProductConfig.Projectroom | undefined;
    "chatintegration-starter"?: ProductConfig.ChatintegrationStarter | undefined;
    "chatintegration-professional"?: ProductConfig.ChatintegrationProfessional | undefined;
    "add-on-200gb"?: ProductConfig.AddOn200Gb | undefined;
    "add-on-500gb"?: ProductConfig.AddOn500Gb | undefined;
    "add-on-1tb"?: ProductConfig.AddOn1Tb | undefined;
    "chat-agent"?: ProductConfig.ChatAgent | undefined;
}

export namespace ProductConfig {
    export interface Developer {
        id?: Developer.Id | undefined;
    }

    export namespace Developer {
        export const Id = {
            ProdUBhelBg3P9Qpj5: "prod_UBhelBG3P9qpj5",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface Projectroom {
        id?: Projectroom.Id | undefined;
    }

    export namespace Projectroom {
        export const Id = {
            ProdUGc67Pc09UMYuh: "prod_UGc67PC09uMYuh",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface ChatintegrationStarter {
        id?: ChatintegrationStarter.Id | undefined;
    }

    export namespace ChatintegrationStarter {
        export const Id = {
            ProdUGbRoO3FiGzPEl: "prod_UGbRoO3FIGzPEl",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface ChatintegrationProfessional {
        id?: ChatintegrationProfessional.Id | undefined;
    }

    export namespace ChatintegrationProfessional {
        export const Id = {
            ProdUGbRxts1OXtMjr: "prod_UGbRxts1OXtMJR",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface AddOn200Gb {
        id?: AddOn200Gb.Id | undefined;
    }

    export namespace AddOn200Gb {
        export const Id = {
            ProdUGbydQqsDqRq9O: "prod_UGbydQqsDQRq9o",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface AddOn500Gb {
        id?: AddOn500Gb.Id | undefined;
    }

    export namespace AddOn500Gb {
        export const Id = {
            ProdUGbzEwRzrMBkMq: "prod_UGbzEwRzrMBkMq",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface AddOn1Tb {
        id?: AddOn1Tb.Id | undefined;
    }

    export namespace AddOn1Tb {
        export const Id = {
            ProdUGc0O1J6KjrMbr: "prod_UGc0o1j6kjrMBR",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }

    export interface ChatAgent {
        id?: ChatAgent.Id | undefined;
    }

    export namespace ChatAgent {
        export const Id = {
            ProdTsYpaQ8BCYpBjh: "prod_TSYpaQ8bCYpBJH",
        } as const;
        export type Id = (typeof Id)[keyof typeof Id];
    }
}
