// This file was auto-generated by Fern from our API Definition.

export interface UploadResponse {
    file_id?: string | undefined;
    filename?: string | undefined;
    url?: string | undefined;
}
