// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../core/index.js";

/**
 * @example
 *     {}
 */
export interface UploadFileRequest {
    /** The file to upload (PDF, TXT, DOCX, etc.) */
    file?: core.file.Uploadable | undefined;
    /** Optional JSON metadata associated with the file */
    metadata?: string;
}
