// This file was auto-generated by Fern from our API Definition.

import type * as ConcreteApi from "./api/index.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace ConcreteApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ConcreteApiClient {
    protected readonly _options: NormalizedClientOptions<ConcreteApiClient.Options>;

    constructor(options: ConcreteApiClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {ConcreteApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.getHealth()
     */
    public getHealth(
        requestOptions?: ConcreteApiClient.RequestOptions,
    ): core.HttpResponsePromise<ConcreteApi.HealthStatus> {
        return core.HttpResponsePromise.fromPromise(this.__getHealth(requestOptions));
    }

    private async __getHealth(
        requestOptions?: ConcreteApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<ConcreteApi.HealthStatus>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ConcreteApiEnvironment.Default,
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ConcreteApi.HealthStatus, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ConcreteApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/health");
    }

    /**
     * @param {ConcreteApi.UploadFileRequest} request
     * @param {ConcreteApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.uploadFile({})
     */
    public uploadFile(
        request: ConcreteApi.UploadFileRequest,
        requestOptions?: ConcreteApiClient.RequestOptions,
    ): core.HttpResponsePromise<ConcreteApi.UploadResponse> {
        return core.HttpResponsePromise.fromPromise(this.__uploadFile(request, requestOptions));
    }

    private async __uploadFile(
        request: ConcreteApi.UploadFileRequest,
        requestOptions?: ConcreteApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<ConcreteApi.UploadResponse>> {
        const _body = await core.newFormData();
        if (request.file != null) {
            await _body.appendFile("file", request.file);
        }

        if (request.metadata != null) {
            _body.append("metadata", request.metadata);
        }

        const _maybeEncodedRequest = await _body.getRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ..._maybeEncodedRequest.headers }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ConcreteApiEnvironment.Default,
                "upload",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ConcreteApi.UploadResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ConcreteApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/upload");
    }

    /**
     * @param {ConcreteApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.startVectorUpdate()
     */
    public startVectorUpdate(
        requestOptions?: ConcreteApiClient.RequestOptions,
    ): core.HttpResponsePromise<ConcreteApi.VectorUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startVectorUpdate(requestOptions));
    }

    private async __startVectorUpdate(
        requestOptions?: ConcreteApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<ConcreteApi.VectorUpdateResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ConcreteApiEnvironment.Default,
                "start_vector_update",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ConcreteApi.VectorUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ConcreteApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/start_vector_update");
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
