// This file was auto-generated by Fern from our API Definition.

export const ConcreteApiEnvironment = {
    Default: "https://api.concrete.example.com/v1",
} as const;

export type ConcreteApiEnvironment = typeof ConcreteApiEnvironment.Default;
