openapi: 3.1.0
info:
  title: Concrete API
  description: The single source of truth for the Concrete SDK
  version: 0.0.1
servers:
  - url: https://api.concrete.example.com/v1

paths:
  /health:
    get:
      summary: Health Check
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
  /upload:
    post:
      summary: Upload a file
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file to upload (PDF, TXT, DOCX, etc.)
                metadata:
                  type: string
                  description: Optional JSON metadata associated with the file
      responses:
        '200':
          description: File successfully uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
  /start_vector_update:
    post:
      summary: Start vector update
      operationId: startVectorUpdate
      responses:
        '200':
          description: Vector update started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VectorUpdateResponse'

components:
  schemas:
    Product:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    
    ProductConfig:
      type: object
      properties:
        developer:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UBhelBG3P9qpj5"]

        projectroom:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UGc67PC09uMYuh"]
        chatintegration-starter:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UGbRoO3FIGzPEl"]
        chatintegration-professional:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UGbRxts1OXtMJR"]
        add-on-200gb:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UGbydQqsDQRq9o"]
        add-on-500gb:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UGbzEwRzrMBkMq"]
        add-on-1tb:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_UGc0o1j6kjrMBR"]
        chat-agent:
          allOf:
            - $ref: '#/components/schemas/Product'
            - type: object
              properties:
                id:
                  enum: ["prod_TSYpaQ8bCYpBJH"]
                  
        



    HealthStatus:
      type: object
      properties:
        status:
          type: string
          example: "up"
        version:
          type: string
          example: "1.0.0"
    UploadResponse:
      type: object
      properties:
        file_id:
          type: string
        filename:
          type: string
        url:
          type: string
    VectorUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
